name: 'TriggerJenkinsBuild'
description: 'Trigger Jenkins build with parameters'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  jenkinsUrl:  
    description: 'URL to Jenkinsserver'
    required: true
  env:
    description: 'Environment'
    required: true
  token:  
    description: 'Token'
    required: true
  username:
    description: 'Username'
    required: true
  job:  
    description: 'Name of job'
    required: true
  tag:
    description: 'Tag'
    required: false
    default: ''
outputs:
  time: 
    description: 'The time the job is posted to jenkins'
runs:
  using: 'node12'
  main: 'index.js'
