name: 'TriggerJenkinsBuild'
description: 'Trigger Jenkins build with parameters'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  jenkinsUrl:  
    description: 'URL to Jenkinsserver'
    required: true
  env:
    description: 'environment'
    required: true
  token:  
    description: 'Token'
    required: true
  job:  
    description: 'Name of job'
    required: true
  params:  
    description: 'Json with "name":"value" params'
    required: false
outputs:
  time: 
    description: 'The time the job is posted to jenkins'
runs:
  using: 'node12'
  main: 'index.js'
