on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - uses: hofry/jenkins-action@master
        with:
          jenkinsUrl: http://188.166.119.105:8080/
          token: testtoken
          tag: ${github.ref}
